### ISSUE TITLE
reread documentation

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/pixelfed_ynh#106]
Seems that there are improvements in the [documentation](https://docs.pixelfed.org/installing-pixelfed/configuring-queue.html), maybe we should implement some of them in pixelfed_ynh

**Comment by lapineige** [comment]
Well I did not understood a thing a that horizon stuff, now I least I know what's its purpose, but I've no idea what are the failed jobs on my server and how to resolve them…
At least it seems activated in my case. Did you activate horizon by default in the package ?

**Comment by lapineige** [comment]
That garbage control stuff https://docs.pixelfed.org/running-pixelfed/administration.html#remove-unused-media is interesting. I wonder if we should add a cron job or just document this in the readme for advanced users.

**Comment by yalh76** [comment]
> 
> 
> Well I did not understood a thing a that horizon stuff, now I least I know what's its purpose, but I've no idea what are the failed jobs on my server and how to resolve them…
> At least it seems activated in my case. Did you activate horizon by default in the package ?

Yes Horizon is included by default:
https://github.com/YunoHost-Apps/pixelfed_ynh/blob/10c3703567d1e9504ea4f298778464c7dd561470/scripts/install#L176

**Comment by yalh76** [comment]
> 
> 
> That garbage control stuff https://docs.pixelfed.org/running-pixelfed/administration.html#remove-unused-media is interesting. I wonder if we should add a cron job or just document this in the readme for advanced users.

Yes I what I though too, so I added the cron job
