### ISSUE TITLE
get ride of /var/log/$app stuff

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/pixelfed_ynh#107]
There are several places in the package that refer to `/var/log/$app` but I'm not sure if pixelfed_ynh can log something... 

If it can log thing we should check that it logs them... If not, references to that should be removed

**Comment by lapineige** [comment]
I have no `/var/log/$app` on my server.
Logging could be used for fail2ban at least, but I don't know if pixelfed log anything or not.

**Comment by yalh76** [comment]
I v'e added creation of the log file in https://github.com/YunoHost-Apps/pixelfed_ynh/blob/fdd125cfa5c3dd819b73927416635538aafe7d56/scripts/install#L146-L148 :) so we will keep /var/logs

**Comment by lapineige** [comment]
Let's see if it logs failed connection attempts, and if that case we could setup a fail2ban rule.

**Comment by yalh76** [comment]
I'm really not sure that connection attempts are logged. If you have time to do some test on a test pixelfed_ynh on the branch https://github.com/YunoHost-Apps/pixelfed_ynh/tree/from_documentation let me know...

**Comment by lapineige** [comment]
Well, if someone else doesn't do it before me, I'm surely going to try… but I don't have time yet.
