### ISSUE TITLE
Unit pixelfed-horizon.service not found.

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/pixelfed_ynh#111]
Using latest master, I found out that the pixelfed-horizon service doesn't exist.
`Failed to start pixelfed-horizon.service: Unit pixelfed-horizon.service not found.`

**Comment by yalh76** [comment]
Seems legit, since 0.10.9~ynh2, pixelfed-horizon service has been removed to use supervisor

**Comment by lapineige** [comment]
Ok, then I guess that this service is still registered in yunohost admin and that we should remove it ?
