### ISSUE TITLE
Uncomment extension in php.ini

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost-Apps/pixelfed_ynh#121]
Hey there,
I don't know if I made a mistake or not but as I was reading this officiel doc https://docs.pixelfed.org/install-guides/arch.html#preparing-a-machine I discovered there were some extension to declare in the php.ini

![Capture d’écran 2020-10-03 à 16 57 33](https://user-images.githubusercontent.com/764332/94994691-91d93b00-0599-11eb-9f23-09b91fecfdad.png)

So I uncommented what was there and added a couple of lines missing. Then restarted phpfpm. I dunno if it helps or if I did it for nothing or worse if it's not adapted to this installation :/

**Comment by yalh76** [comment]
which file did you modify ?

**Comment by ImaCrea** [comment]
Hi,
I edited /etc/php/7.3/fpm/php.ini

**Comment by yalh76** [comment]
I made some test, there is no need to uncomment in `/etc/php/7.3/fpm/php.ini` 
The extension are activated with the files in ` /etc/php/7.3/fpm/conf.d/*.ini` files
