### ISSUE TITLE
can´t change URL 

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/pixelfed_ynh#132]
can´t change URL 
https://paste.yunohost.org/raw/lahowijado
any idea - THANKs

**Comment by rocky-III** [comment]
still need some help.
“Change URL” feature in the panel admin did not work
now
did some changes in Nginx ( https://forum.yunohost.org/t/url-change-for-nextcloud-or-any-other-application/7319/5 )

and the .env file 

and did

        php$phpversion artisan config:clear
	php$phpversion artisan config:cache
	php$phpversion artisan route:clear
	php$phpversion artisan route:cache
	php$phpversion artisan horizon:purge

Now everything seams to work fine with the new URL but on the pages 

/accont-name
and
/discover

the images thumps are not showing up. If I click on them, the main images is visible as it should.

So there seams to be one more setting that hast to be adjusted. Can some one help ? THANKS

all new upload are working 100% also with the  thumps

**Comment by yalh76** [comment]
change_url should work for now
