### ISSUE TITLE
Permission issues after upgrade from 0.10.10~ynh1 to  0.10.10~ynh2 

### ISSUE THREAD

**Issue by nocci-sl** [YunoHost-Apps/pixelfed_ynh#135]
### Describe the bug

After upgrading from "0.10.10 ynh1" to  "0.10.10 ynh2" I cant see any images and the maybe CSS seems to be broken.

In the nginx error log it show tons of "Permission denied" rows regarding images. 

### Context

- Hardware: *VPS Hetzner*
- YunoHost version: 4.1.8 (stable).
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

Just use the "System update" in the admin ui. I did nothing else.

### Expected behavior

I would have expected that pixelfed got an working update. Nothing else.
I did not do something special and the rollback was easy and everything was fine. But even a second try to update the software gave me the same - not working - results.

Maybe there is something wrong with the permissions... but I am not a great help investigating that issue I guess. 
Anyway... thank you all for your help! :D

### Logs
Install-Log
https://paste.yunohost.org/raw/eliqeqireh

Error-Log (Nginx)
https://paste.yunohost.org/raw/umamohivik

**Comment by yalh76** [comment]
I will look at that :)
