### ISSUE TITLE
Large size photos fail to upload without warning

### ISSUE THREAD

**Issue by PaulaToThePeople** [YunoHost-Apps/pixelfed_ynh#141]
### Describe the bug

If I try to upload a photo that is larger than a certain size (mbs) I get an "Oops, something went wrong! An unexpected error occurred." error after reaching 100%.
The same happens with 2 different instances installed via Yunohost, but it works with other instances

### Context

Hardware: VPS bought online: Hetzner cloud cx21
YunoHost version: 4.2.4 (stable).
I have access to my server : through the webadmin
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

### Steps to reproduce

1. Install Pixelfed via Yunohost
2. try to upload a file that has e.g. 7mb.

### Expected behavior

I'd expect the upload works or I get a message before the upload starts, that the file is too large.

**Comment by lapineige** [comment]
There is a limit to the max upload file size.
We raised it to 50M a while ago : https://github.com/YunoHost-Apps/pixelfed_ynh/issues/120#issuecomment-829520759

You might want to increase it.

> or I get a message before the upload starts, that the file is too large.

That's something we can't do, it's on Pixelfed side. (yeah, I know, the UX is pretty bad)
