### ISSUE TITLE
Line breaks dissapear when posting

### ISSUE THREAD

**Issue by PaulaToThePeople** [YunoHost-Apps/pixelfed_ynh#149]
### Describe the bug

When writing a post with lots of text its wise to include paragraphs and line breaks, but sometimes when posting the line breaks disappear and the text is just one block.

### Steps to reproduce

It happens randomly, but it should only take a few tries to reproduce, as it happens often.

1. Click on "compose"
2. choose "new post"
3. upload a picture
4. In the "write a caption field" write a long text with paragraphs and line breaks.

*If applicable and useful, add screenshots to help explain your problem.*

**Comment by lapineige** [comment]
Does it happens in both MetroUI and MomentUI, and maybe when seen from another software (ie. mastodon, …) or Pixelfed instance ?

**Comment by yalh76** [comment]
Feel free to reopen this issue
