### ISSUE TITLE
Lots of locations are missing

### ISSUE THREAD

**Issue by PaulaToThePeople** [YunoHost-Apps/pixelfed_ynh#150]
### Describe the bug

When composing a post there are a lot of locations missing in the "add location" menu.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.2.7 (stable)
- I have access to my server:  through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- click "compose"
- choose "new post"
- upload an image
- click "add location"
- search e.g. for "vienna" or "wien"

### Expected behavior

On pixelfed.de searching for "Vienna" will find "Vienna, Austria" and searching for "Wien" will find "Wiener Neustadt", "Wiener Neudorf", "Baden bei Wien",...
On a Pixelfed ynh instance "Vienna" yields no results and searching for "wien" only yields "Schottwien, Austria".

**Comment by lapineige** [comment]
Uh, that is strange…

Do you know the version number of pixelfed.de instance ?

**Comment by PaulaToThePeople** [comment]
v0.11.0

Same as Pixelfed.de

**Comment by lapineige** [comment]
Ok… then I have no clue, I don't see a reason why there would be such a difference. I don't know how that location database (?) works (and I never used it).
I believe we might need some help from Pixelfed devs…

**Comment by lapineige** [comment]
Just in case : does it work now on v0.11.2 ? #163
