### ISSUE TITLE
"Something went wrong" error after restoring backup to another server

### ISSUE THREAD

**Issue by ashemsay** [YunoHost-Apps/pixelfed_ynh#152]
### Describe the bug

When I login I have this message:
```
Something went wrong
We cannot process your request at this time, please try again later. Go back to Pixelfed.
```

### Context

- Hardware: *VM on dedicated server*
- YunoHost version: *4.2.8.1*
- I have access to my server: *Through SSH + through the webadmin + direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  I migrated the application from a yunohost server to another with a simple `yunohost backup create --apps pixelfed -n mybackup` on the source server, transfered the backup then `yunohost backup restore mybackup --apps` on the destination server.
  Yunohost diagnosis says everything is fine
- Using, or trying to install package version/branch: master (well the default one, I just did `yunohost app install pixelfed` when I installed on the orignal server)

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to homepage*
   2. *Enter email, password and click on 'LOGIN'*
   
### Expected behavior

*User is logged in*

### Logs

By tailing multiple files when the error occurs, I can see:

/var/log/nginx/pixelfed.domain.tld-access.log
```
x.x.x.x - - [30/Aug/2021:22:27:07 +0200] "POST /login HTTP/2.0" 500 4978 "https://pixelfed.domain.tld/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"

Nothing in:

- /var/log/nginx/error.log
- /var/log/pixelfed/pixelfed-horizon.log
- pixelfed.domain.tld-error.log
```

**Comment by lapineige** [comment]
Can you try to restart `php7.3-fpm` ?

**Comment by ashemsay** [comment]
> Can you try to restart `php7.3-fpm` ?

No luck

**Comment by lapineige** [comment]
If you upgrade to v0.11.2 (just run Yunohost app upgrade process), does it solve the issue ? #163

**Comment by ashemsay** [comment]
It seems to be working fine, although the pixelfed app on android does not work anymore but that's not a real issue, I can use FF.

**Comment by lapineige** [comment]
Ok, that's good to know and kind of problematic for the app…
Thanks for sharing this :)

**Comment by ashemsay** [comment]
Little mistake, the app is not pixelfed, it's pixeldroid. I get a "Impossible d'enregistrer l'application sur ce server" (Could not register the application on this server).
I could create another issue if you would like to keep track of that.

**Comment by lapineige** [comment]
I think that would be a good think, especially if you could document it (with for instance Nginx/Pixelfed/Pixeldroid logs showing a particular error…) if you have the time and ability to do it :)

Maybe it's related to https://github.com/YunoHost-Apps/pixelfed_ynh/issues/140 ?

**Comment by ashemsay** [comment]
I tried the php artisan commands, now I get the authorization page everytime but can't login, anyway I created a new issue: #167
