### ISSUE TITLE
Unable to run php artisan cache:clear

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/pixelfed_ynh#164]
### Describe the bug

When running `php artisan cache:clear`, I get:

```
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.33-1+0~20211119.91+debian10~1.gbp618351.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.33-1+0~20211119.91+debian10~1.gbp618351. in /var/www/pixelfed/vendor/composer/platform_check.php on line 24`
```

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: 0.11.2

### Steps to reproduce

    sudo -s
    cd /var/www/pixelfed
    php artisan cache:clear

### Expected behavior

SUccesfully clearing the cache

**Comment by lapineige** [comment]
> php artisan cache:clear

Use `php7.4 artisan cache:clear`, if it is not specified it will fallback to the default php version (here, php7.3).

**Comment by xplosionmind** [comment]
> Use `php7.4 artisan cache:clear`

Great! This way, it works. Thanks a lot.
