### ISSUE TITLE
The page has expired due to inactivity.  Please refresh and try again. 

### ISSUE THREAD

**Issue by lesamarien** [YunoHost-Apps/pixelfed_ynh#17]
Bonjour

1 - Je viens d'installer PixelFed et quand je veux créer un compte, je tombe sur la page : 
The page has expired due to inactivity. Please refresh and try again. Impossible donc de creer un compte.

2 - Dans le fichier de conf de nginx, il faut ajouter la ligne : try_files $uri $uri/ /index.php?$args; afin d'éviter une erreur 404

Si vous avez une idée
Merci de votre aide

Hello

1 - I just installed PixelFed
The page has expired due to inactivity. Please refresh and try again. Impossible to create an account.

2 - In the Nginx configuration file, add the line: try_files $ uri $ uri / /index.php?$args; to avoid a 404 error.

If you have an idea
Thank you for your help

**Comment by Jibec** [comment]
Hello, thanks for your issue, please wait a few more days and what is said in this issue https://github.com/YunoHost-Apps/pixelfed_ynh/issues/6

the app is not working for now, but it should be better soon
