### ISSUE TITLE
Can't send confirmation email

### ISSUE THREAD

**Issue by blogdemoi** [YunoHost-Apps/pixelfed_ynh#174]
### Describe the bug
After Pixelfed installation, I register and an e-mail is sent to confirm my e-mail address. However on clicking on this mail it opens a login web page, I log in, then I have a webpage stating:

> Sorry, this page isn't available.
> The link you followed may be broken, or the page may have been removed. [Go back to Pixelfed.](https://pixelfed.xxx.org/)
> 

I see that this behavior was previously reported here: 

https://github.com/pixelfed/support/issues/84#

and

https://github.com/pixelfed/support/issues/107#

### Context

- Hardware:  Raspberry Pi at home / Internet Cube with VPN 
- YunoHost version: [YunoHost](https://yunohost.org/) 4.3.6.3 (stable)
- I have access to my server: *Through SSH | through the webadmin 
- Using package version/branch: 0.11.2~ynh1

### Logs
I just have the logs of the installation, can't find other logs about my problem.

**Comment by lapineige** [comment]
For the record, the related forum thread: https://forum.yunohost.org/t/pixelfeld-impossible-de-confirmer-mon-adresse-e-mail/19552

**Comment by ajtakrajta** [comment]
I used following workaround to get confirmed email:

root@yuno:~# sudo php8.0 /var/www/pixelfed/artisan db
pixelfed=> update users set email_verified_at=now() where username = 'xyz';

**Comment by lapineige** [comment]
Ok... what is that command doing O_o ?

Thanks for sharing this !

**Comment by ajtakrajta** [comment]
First command connects to Pixelfed database, the second command modifies data so it looks like the user confirmed email.

There's probably another workaround by disabling email verification using  ENFORCE_EMAIL_VERIFICATION=false in 
file /var/www/pixelfed/.env .
