### ISSUE TITLE
Update from 0.11.2 to 0.11.3 fails

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/pixelfed_ynh#180]
### Describe the bug

Update from `0.11.2~ynh1` to `0.11.3~ynh1`

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: *0.11.2~ynh1*

### Steps to reproduce

- Performed upgrade commanf
    ```sh
    sudo yunohost app upgrade pixelfed
    ```

### Expected behavior

*The update occurs normally*

**Comment by yalh76** [comment]
Did you changed the APP_TIMEZONE in the .env file ? 
Seems you timezone is `CEST`, it's invalid

**Comment by xplosionmind** [comment]
Right. Now fixed and working.
