### ISSUE TITLE
config question regarding Horizon

### ISSUE THREAD

**Issue by tompatulpan** [YunoHost-Apps/pixelfed_ynh#187]
My Pixelfed instance is installed on pixelfed.domain_1.tld
I have two domains on my YH server
domain_1.tld
domain_2.tld

I did see my 2nd domain in Pixelfed admin under Horizon and checked it:
`root@domain_2:/var/www/pixelfed# php artisan horizon:supervisors
+--------------------------------+------+---------+--------------------------------------------------------------------------------------------------------------------+-----------+
| Name                           | PID  | Status  | Workers                                                                                                            | Balancing |
+--------------------------------+------+---------+--------------------------------------------------------------------------------------------------------------------+-----------+
| domain_2tld-aomb:supervisor-1 | 1746 | running | redis:high (1), redis:default (1), redis:feed (1), redis:low (1), redis:story (1), redis:delete (1), redis:mmo (1) | auto      |
+--------------------------------+------+---------+--------------------------------------------------------------------------------------------------------------------+-----------+`

I just want to check/know if this is correct?

edit: That was not pretty, my point is this part - `domain_2tld-aomb:supervisor-1`

edit2: note that the hostname of the server is domain_2.tld

**Comment by yalh76** [comment]
I don't understand what you are trying to do ...

**Comment by tompatulpan** [comment]
I'm just trying to understand that everything is working as expected and when seeing my other domain name in a YH app using a total different one, I didn't understand why and that it would be good to check with devs?
But now I just think the answer is the hostname that is seen in Horizon (that was the same as this other domain).
