### ISSUE TITLE
warning installation / pixelfed-horizon missing

### ISSUE THREAD

**Issue by tomtoom1978** [YunoHost-Apps/pixelfed_ynh#190]
Hello, after a fresh install of pixelfed  version: 0.11.4~ynh1, i can't connect to other and cannot post picture.
Thanks, Am I this only one?

Info: Installing pixelfed...
Info: [....................] > Validating installation parameters...
Info: [+...................] > Storing installation settings...
Info: [#+..................] > Installing dependencies...
Info: [##+.................] > Configuring system user...
Info: [###+................] > Creating a PostgreSQL database...
Info: [####+...............] > Creating a Redis database...
Info: [#####+..............] > Setting up source files...
Info: [######+.............] > Configuring PHP-FPM...
Info: [#######+............] > Configuring NGINX web server...
Info: [########+...........] > Installing composer dependencies...
Info: [#########+..........] > Creating log file...
Info: [##########+.........] > Adding a configuration file...
Info: [###########+........] > Configuring a supervisor service...
Info: [############+.......] > Deploying...
Warning: fatal: not a git repository (or any of the parent directories): .git
Info: [#############+......] > Installing the cron file...
Info: [##############+.....] > Configuring log rotation...
Info: [###############+....] > Integrating service in YunoHost...
Info: [################+...] > Starting a supervisor service...
Warning: Please wait, the service pixelfed-horizon is updateing..........................................................................................................................................................................................................................................................................................................
Warning: The service pixelfed-horizon didn't fully executed the action update before the timeout.
Warning: Please find here an extract of the end of the log of the service pixelfed-horizon:
Info: [#################+..] > Configuring permissions...
Info: [##################+.] > Reloading NGINX web server...
Info: [###################+] > Installation of pixelfed completed
Success! Installation completed

**Comment by yalh76** [comment]
can you provide a yunopaste of your install ?

**Comment by lapineige** [comment]
He means the log link that is provided to you after the installation, and available in your administration panel tools.

**Comment by InvisibleManGithub** [comment]
i have this problem.
this is install log?: https://paste.yunohost.org/raw/munopajaxo

**Comment by lapineige** [comment]
Can you share the specifications of your server ? I mean how many CPU cores, how much RAM.
If it's a Raspberry pi or similar just give us the model name.

@yalh76 horizon doesn't start in a 300s timeout frame… I don't know if it's buggy or just in needs of more time or small servers ?

**Comment by InvisibleManGithub** [comment]
> Can you share the specifications of your server ? I mean how many CPU cores, how much RAM. If it's a Raspberry pi or similar just give us the model name.
> 
> @yalh76 horizon doesn't start in a 300s timeout frame… I don't know if it's buggy or just in needs of more time or small servers ?

Ram 4 GB
Core: 2
I do not know the exact processor model provided by my provider

lscpu
`Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
**CPU(s):                          2** cores
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      15
Model:                           6
Model name:                      Common KVM processor
Stepping:                        1
CPU MHz:                         2095.076
BogoMIPS:                        4190.15
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        8 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attem
                                 pted, no microcode; SMT Host state 
                                 unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypas
                                 s disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barrier
                                 s and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB condit
                                 ional, IBRS_FW, STIBP disabled, RSB
                                  filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 
                                 apic sep mtrr pge mca cmov pat pse3
                                 6 clflush mmx fxsr sse sse2 ht sysc
                                 all nx pdpe1gb rdtscp lm constant_t
                                 sc nopl xtopology cpuid tsc_known_f
                                 req pni pclmulqdq ssse3 fma cx16 pc
                                 id sse4_1 sse4_2 x2apic movbe popcn
                                 t aes xsave avx f16c rdrand hypervi
                                 sor lahf_lm abm cpuid_fault invpcid
                                 _single pti ssbd ibrs ibpb fsgsbase
                                  bmi1 avx2 smep bmi2 erms invpcid x
                                 saveopt arat
`

**Comment by lapineige** [comment]
Ok so I don't expect that would be the trouble… I don't know what's going on, I suppose I would need detail horizon-service log from that installation time…
I don't really how time to setup a testing environment for that…
Maybe we should open an issue on Pixelfed repository to gather their insight… I don't know if it's Yunohost related or a bug.

**Comment by InvisibleManGithub** [comment]
I have just conducted an experiment. I returned the old version from the backup. The Federation did not work in it either. The whole world didn't see me. After activating the administrator account and updating the software, Horizon seems to have started (it goes there in the administrator's web interface.) But the federation is also broken, the world does not see me.

Log update: https://paste.yunohost.org/raw/sozerakumo

**Comment by lapineige** [comment]
> The service pixelfed-horizon has correctly executed the action start.

Indeed, horizon started.

I don't know if it is related to federation or not, I don't understand how Pixelfed work…

I have no clue…

Do you see other instances ? If you search an account by its URL ?

**Comment by InvisibleManGithub** [comment]
> Do you see other instances ? If you search an account by its URL ?

Yes, I see. I'm trying to subscribe, write a personal message. But others don't see me

**Comment by InvisibleManGithub** [comment]
@lapineige my problem is over. Others saw me.

about the problem on the topic "horizon is falling"

it is possible that the administrator account was not enabled. that is, the command was not executed
`php7.4 /var/www/pixelfed/artisan user:admin 1`

**Comment by lapineige** [comment]
> @lapineige my problem is over. Others saw me.

Did you do any change ?

> about the problem on the topic "horizon is falling"
it is possible that the administrator account was not enabled. that is, the command was not executed
php7.4 /var/www/pixelfed/artisan user:admin 1

Oh, so Horizon (which seems to be related to admin interface) seems to required an admin account to be created (=registered as such).
