### ISSUE TITLE
Pixelfed Yunohost Stories

### ISSUE THREAD

**Issue by cdedert** [YunoHost-Apps/pixelfed_ynh#195]
How do I turn on the Stories feature on my instance installed through Yunohost?

**Comment by aasandr0** [comment]
> How do I turn on the Stories feature on my instance installed through Yunohost?

Hi,
to do this you need to go to the admin panel at the link: https://your-instance.ltd/i/admin/dashboard
From there go to "Settings" or go to: https://your-instance.ltd/i/admin/settings
and there click on the checkbox "Stories" and then save. 
![image](https://user-images.githubusercontent.com/119762559/205500240-03d60248-5f06-4f14-bae5-797f85bab7f4.png)

**Comment by cdedert** [comment]
OK. 

Looks like my SETTINGS isn't enabled. 

I get this when I go to settings. 

Add ENABLE_CONFIG_CACHE=true in your .env file
and run php artisan config:cache

**Comment by lapineige** [comment]
I thought this was fixed 🤔

Then you need to logging via the command line, edit you `/var/www/pixelfed/.env` file (for instance with `nano /var/www/pixelfed/.env`), add a line with `ENABLE_CONFIG_CACHE=true` then run `cd /var/www/pixelfed & php8.0 artisan config:cache`.
This should fix it and allow you to edit such setting via the admin panel.
Btw, this is the file to edit if you want to enable stories from the command line.

**Comment by cdedert** [comment]
I ran the commands mentioned above and I now have access to the settings.  Thanks!

**Comment by lapineige** [comment]
Great ! 🎉
