### ISSUE TITLE
Oops. Something went wrong after update

### ISSUE THREAD

**Issue by Schdefoon** [YunoHost-Apps/pixelfed_ynh#202]
Hello,

I did an update from 0.11.4-ynh4 to 0.11.4-ynh5 on February 19th and did not notice any error while updating.
When posting a status now I always get a message "Oops. Something went wrong". I ignored this message because everything seemed to be ok. The status is visible in the timeline.
Now I found out that there are problems: In the database tables "hashtag" and "status_hashtags" no new entries are written. And in the table "statuses" the field "entities" stays empty.

Is there a way to find what's the problem on my instance running on a local RaspberryPi?

Best regards

**Comment by Schdefoon** [comment]
Thank you very much for your help.
What have I to do to force an upgrade for pixelfed?
I tried the command `yunohost app upgrade pixelfed`
The response was 
- Info: Now upgrading pixelfed...
- Success! pixelfed is already up-to-date
- Success! Upgrade complete

I did not post a new status yet to see if the situation changed

**Comment by lapineige** [comment]
Use `yunohost app upgrade pixelfed --force`

**Comment by Schdefoon** [comment]
Ok, thanks a lot.
But unfortunately the problem still exists on my pixelfed instance after the forced upgrade.
I think I'll take the time to run some tests on my desktop PC with browser debugging tools and look at the log files.
Maybe I can find some more hints.

**Comment by lapineige** [comment]
Is horizon service running ?
What does it says in the admin interface ?

**Comment by lapineige** [comment]
Thanks for all that work !

I will change this on default config.
