### ISSUE TITLE
Sync with upstream repo

### ISSUE THREAD

**Issue by jcrabapple** [YunoHost-Apps/pixelfed_ynh#207]
Please sync with upstream repo as there were a couple critical fixes pushed early this morning.

**Comment by lapineige** [comment]
You mean security fixes ?
We rely on released version, but if it's important security fixes we may switch to a specific commit number (naming the version may be an issue in that case) to include them.

**Comment by jcrabapple** [comment]
Yes this is #209. It's critical to getting images to show properly. Thank you.
