### ISSUE TITLE
Add fail2ban protection against brute force

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/pixelfed_ynh#22]
As this app expose a public login form, it should be protected against password brute force with fail2ban.

The account is not yet linked to the SSO / yunohost account, so it might not be a big security issue for the rest of the instance… yet it would be better to add that protection.

PS: I write that here as a reminder, I guess you have other priorities right now ;)
(and maybe someone will use that issue to get involved with a quick contribution :)

**Comment by lapineige** [comment]
Does Pixelfed provide some logs for (failed) login attempts ? With the IP ?

**Comment by yalh76** [comment]
> Does Pixelfed provide some logs for (failed) login attempts ? With the IP ?

I don't know, have to be checked on [Pixelfed project](https://github.com/pixelfed/pixelfed)

**Comment by yalh76** [comment]
Feel free to make a PR for the fail2ban

**Comment by OniriCorpe** [comment]
> Does Pixelfed provide some logs for (failed) login attempts ? With the IP ?

the answer is no

none of `/var/log/pixelfed/pixelfed.log`, `/var/log/pixelfed/pixelfed-horizon.log` or nginx logs  provides the necessary information

so closing the issue...

**Comment by lapineige** [comment]
That's an upstream issue then :(
