### ISSUE TITLE
Default mail settings in .env do not work out of the box

### ISSUE THREAD

**Issue by themancalledjakob** [YunoHost-Apps/pixelfed_ynh#228]
### Describe the bug

*Default mail settings in .env do not work out of the box.*

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 11.2
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce
```sh
sudo yunohost app install pixelfed
```
   1. *Go to pixelfed instance with browser*
   2. *Create a new user and ask to send confirmation email*
   3. *“Something went wrong” - page opens*

### Expected behavior

*Send confirmation email instead.*

### Proposal

Afaik there are two ways to solve this issue.

#### Option 1 - using sendmail
Either the default `.env` could be adjusted like so:
https://github.com/themancalledjakob/pixelfed_ynh/blob/fix-mail-sendmail/conf/.env#L87

#### Option 2 - smtp with dedicated system user [PR](https://github.com/themancalledjakob/pixelfed_ynh/blob/fix-mail-smtp/conf/.env#L89)
or, the settings could be updated to fit in the new way of connecting apps with the mailserver as described [here](https://yunohost.org/fr/packaging_apps_resources#system-user)
Which would probably be done like this:
https://github.com/themancalledjakob/pixelfed_ynh/blob/fix-mail-smtp/manifest.toml#L45
and
https://github.com/themancalledjakob/pixelfed_ynh/blob/fix-mail-smtp/conf/.env#L86-L94

the second option seems more elegant to me, as it follows yunohost instructions, possibly more future proof.
the settings would have to be verified though, in my changes i am not sure whether port `25` or `587`should be set. with the correct settings, i think this would be the way to go though.

@lapineige what do you think?

**Comment by themancalledjakob** [comment]
btw, i'm testing a fresh install with smtp via dedicated system user config right now to make sure it works

**Comment by lapineige** [comment]
Solved.
