### ISSUE TITLE
Add an interface to set an user as admin

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/pixelfed_ynh#23]
Right know the people who install Pixelfed needs to type a command to give admin rights to an account.
I'd would be better (=more accessible) to expose that action thought Yunohost UI.

I don't know if it is (yet ?) possible to create an account when the app is installed (does Pixelfed support that API ?), in that case I suppose I would be better to setup the first account during installation, and give it admin rights.
If it's not (yet) possible, an option in Yunohost admin UI would be cool :)

And it might also be better to have the option to do it after installing the app (for instance, later you want to add another admin to your app).

We could use Yunohost app actions/config panel for that (see: https://forum.yunohost.org/t/yunohost-3-1-minor-stable-release-version-stable-mineure/5445).

What do you think ?

**Comment by yalh76** [comment]
Maybe we can wait a final release before improving package ?
Pixelfed is still a beta
