### ISSUE TITLE
Add some Pixelfed admin options as app actions / in Yunohost admin UI

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/pixelfed_ynh#24]
Right now registration are open by default, and admins needs to go to `/var/www/pixelfed` and edit `.env` file to close it.
(as referenced here: https://docs.pixelfed.org/master/configuration.html#pixelfed-configuration)

As some people would like to close the registration, it would be more accessible to expose that action thought the command line and the admin interface.
Maybe we could use the app actions and app config panels features implemented in Yunohost 3.1 ? (https://forum.yunohost.org/t/yunohost-3-1-minor-stable-release-version-stable-mineure/5445)

Should we also include some extra settings, for instance account size limit, that kind of things ?
I suppose it will be added in Pixelfed admin interface in the future, so I'm not sure it's worth doing it right now (but we can add some instructions in the readme :).

What do you think ?

**Comment by lapineige** [comment]
> but we can add some instructions in the readme

PR here #25

**Comment by yalh76** [comment]
Seems to be planned for 0.9.0

![Capture](https://user-images.githubusercontent.com/30271971/55843719-f6990e00-5b39-11e9-8ce4-e7b9b051c986.PNG)

**Comment by lapineige** [comment]
Ok, so I guess we can close this.
