### ISSUE TITLE
Photos not showing (again)

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/pixelfed_ynh#262]
I see this being discussed in the past https://github.com/YunoHost-Apps/pixelfed_ynh/issues/223 https://github.com/YunoHost-Apps/pixelfed_ynh/issues/211. I just setup a pixelfed instance and no photos are being displayed:

![image](https://github.com/YunoHost-Apps/pixelfed_ynh/assets/38043315/7c0d7106-73c0-4613-b6f7-263c9f662f34)

I just wanted to make you aware....

**Comment by lapineige** [comment]
Did you check file rights for this picture ?
Could you force an upgrade of Pixelfed (yes, to that same version) ?

**Comment by tio-trom** [comment]
We fixed it somehow - a friend is in charge of it now and will report here if needed. I will close this comment for now. Thanks for the reply!
