### ISSUE TITLE
Unnecessary Script

### ISSUE THREAD

**Issue by vibhi19** [YunoHost-Apps/pixelfed_ynh#34]
I Just installed and testing how it is and ready for use or not I installed Testing branch so i can get faster updates.

I just checked on gtmetrix and seeing that it load Yunohost script which dont even needed here are script which are being loaded 

although they return 404 Error but it should be removed 

```
https://nextme.tk/ynh_portal.js
https://nextme.tk/ynh_overlay.css
https://nextme.tk/ynhtheme/custom_portal.js
https://nextme.tk/ynhtheme/custom_overlay.css
https://nextme.tk/ynh_overlay.css
https://nextme.tk/ynhtheme/custom_portal.js
https://nextme.tk/ynhtheme/custom_overlay.css

```

**Comment by yalh76** [comment]
The scripts are necessary to have the yunohost tile.

Even if for now the tile is not available, we will keep the script.

I open a dedicated issue for the tile not available: https://github.com/YunoHost-Apps/pixelfed_ynh/issues/41
