### ISSUE TITLE
domain/pixelfed/login redirects to domain/yunohost/sso/

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/pixelfed_ynh#4]
After installing pixelfed in a subfolder I get a redirection that renders the application unusable. 

Maybe if I find the time, I'll try an installation on /

**Comment by Jibec** [comment]
Well, this app is not working. It is normal.

**Comment by Jibec** [comment]
hello, should be fixed soon, please follow this issue https://github.com/YunoHost-Apps/pixelfed_ynh/issues/6
