### ISSUE TITLE
Instalation results in 502 on nginx

### ISSUE THREAD

**Issue by AlexSleepy** [YunoHost-Apps/pixelfed_ynh#42]
Installation results in error 502 Bad Gateway on nginx.
Here's the installation log
`Installation complete
The SSOwat configuration has been generated
Installation of pixelfed completed
Reloading nginx web server...
Configuring SSOwat...
fatal: Not a git repository (or any of the parent directories): .git
Reload the service php7.2-fpm
Configuring php-fpm...
Configuring system user...
Reload the service nginx
Configuring nginx web server...
Creating a PostgreSQL database...
Installing dependencies...
Validating installation parameters...
Installing application pixelfed…`
I found the issue #37, but running `php artisan horizon` didn't help and was returning a lot of messages like 
`mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 12582912) (tried to allocate 20480 bytes) in /var/www/pixelfed/bootstrap/cache/routes.php on line 15`
I'm running yuno host on digital ocean droplet with 1gb of ram, if it matters

**Comment by yalh76** [comment]
> 
> 
> Installation results in error 502 Bad Gateway on nginx.
> Here's the installation log
> `Installation complete The SSOwat configuration has been generated Installation of pixelfed completed Reloading nginx web server... Configuring SSOwat... fatal: Not a git repository (or any of the parent directories): .git Reload the service php7.2-fpm Configuring php-fpm... Configuring system user... Reload the service nginx Configuring nginx web server... Creating a PostgreSQL database... Installing dependencies... Validating installation parameters... Installing application pixelfed…`
> I found the issue #37, but running `php artisan horizon` didn't help and was returning a lot of messages like
> `mmap() failed: [12] Cannot allocate memory PHP Fatal error: Out of memory (allocated 12582912) (tried to allocate 20480 bytes) in /var/www/pixelfed/bootstrap/cache/routes.php on line 15`
> I'm running yuno host on digital ocean droplet with 1gb of ram, if it matters

If you have an error 502 Bad gateway, can you check the php7.2-fpm service doing: `service php7.2-fpm status` to check if it's running

**Comment by AlexSleepy** [comment]
Yep, it was stopped. Works now, thanks.
