### ISSUE TITLE
Suis-je bien en version 0.9.0 - Am I in version 0.9.0

### ISSUE THREAD

**Issue by lesamarien** [YunoHost-Apps/pixelfed_ynh#47]
Bonjour

Je viens d'installer la version que tu viens de publier (donc normalement la 0.9.0) mais dans la configuration j'ai ce message : Feature Unavailable: This feature will be released in v0.9.0.  dans Maintenance, Configuration, Features, Storage et Page. Quand je vais dans System, j'ai bien indiqué la version 0.9.0.

Il y a également quelques souci : 
- Je ne vois pas la fédération et je n'arrive pas à ajouter une personne d'une autre instance. Est-ce normal ?

Merci de ton aide

---------------------------------------------------------------------------------------------------------------

Hello

I just installed the version you just published (so normally 0.9.0) but in the configuration I have this message: Feature Unavailable: This feature will be released in v0.9.0. in Maintenance, Configuration, Features, Storage and Page. When I go into System, I indicated version 0.9.0.

There are also some concerns:
- I do not see the federation and I can not add a person from another instance. Is this normal?

thanks for your help

**Comment by yalh76** [comment]
Salut @lesmarien

Pour les options dont tu parles, même si c’est indiqué qu’elles seront implémentés en 0.9.0, elles ne l’ont pas été et du côté de Pixelfed ils n’ont pas changé le texte pour dire que ça serait implémenté en 0.9.1 ou autre.

Concernant la fédération, je viens de vérifier, elle est bien activée par défaut en suivant les indications de pixelfed mais je ne l’ai pas testé... Il faudrait peut être que tu leur demandes.

——
Some features indicated to be available at 0.9.0 are still not implemented in version 0.9.0 and corresponding text has not been changed.

Federation is enable by default but has not been tested on pixelfed_ynh

**Comment by lesamarien** [comment]
Merci de ta réponse rapide

Apparemment, il y a une version 0.9.2. Certaines instances y sont déjà passées. On y trouve également les suggestions que l'on a pas avec la 0.9.0. C'est peut etre avec cette version qu'il y a des modifs. J'attendrais que tu fasses la mise à jour afin de voir si ça évolue.

**Comment by yalh76** [comment]
La 0.9.2 n’est pas encore released, c’est dans la branche testing de pixelfed, on va attendre que la 0.9.2 soit sorti... on est encore dans ses version bêta, autant ne pas ajouter trop d’instabilité ^^

**Comment by lapineige** [comment]
> Concernant la fédération, je viens de vérifier, elle est bien activée par défaut en suivant les indications de pixelfed mais je ne l’ai pas testé... Il faudrait peut être que tu leur demandes.

Elle ne marche pas non plus pour moi.
