### ISSUE TITLE
?init in file stopping php artisan commands

### ISSUE THREAD

**Issue by StopTrackingUs** [YunoHost-Apps/pixelfed_ynh#48]
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/pixelfed/vendor/zendframework/zend-diactoros/src/functions/marshal_uri_from_sapi.php on line 83

I am trying to turn on ActivityPub inbox and sharedinbox, but when I run artisan commands I get this error.

**Comment by StopTrackingUs** [comment]
The syntax errors look like they only effect php7.0 and not updated version.  Can anyone assist me in updating php for the one app? (this should be possible on the docker level)

**Comment by StopTrackingUs** [comment]
This issue can be closed.

**Comment by lapineige** [comment]
Same issue for me :(

**Comment by lapineige** [comment]
Oh ok I just understood what you meant : we need to run `php7.2` in each command instead of just `php artisant [command]`. I guess `php` default to 7.0.
