### ISSUE TITLE
# of Users Bug

### ISSUE THREAD

**Issue by StopTrackingUs** [YunoHost-Apps/pixelfed_ynh#52]
Just a note that currently the number of users on the dashboard reflects the highest UID and not the actual number of users.  This usually wouldn't matter, but I had someone type their email wrong in signing up for my instance.  I deleted the user using artisan, but the User count did not recognize the change.

**Comment by yalh76** [comment]
Maybe it would be better to report directly at https://github.com/pixelfed/pixelfed
We only package the application for Yunohost and we don't fix it.
