### ISSUE TITLE
Labs (experimental features)

### ISSUE THREAD

**Issue by StopTrackingUs** [YunoHost-Apps/pixelfed_ynh#59]
I noticed a few of the experimental features that are not showing up like profile suggestions.  I have a couple of other bugs I was going to put on the main git, but wanted to see if this was one of them.

**Comment by yalh76** [comment]
After checking code the `BETA FEATURES` profile suggestions

https://github.com/pixelfed/pixelfed/blob/d3567aabcf440ff3159ff554368668f664f741b1/resources/views/settings/labs.blade.php#L159-L167

is in the dev branch but the `labs.blade.php` wasn't present in the last release 0.9.0
https://github.com/pixelfed/pixelfed/tree/v0.9.0/resources/views/settings
