### ISSUE TITLE
upgrade pixelfed to a recent version (was: Version 0.1.9)

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/pixelfed_ynh#6]
Hi
Version 0.1.9 has been released. It would nice to have this app for yuohost.

**Comment by anmol26s** [comment]
It would so nice. I have so much learn and help. I would love to be involve with you in this package.

**Comment by lapineige** [comment]
There is a 0.5.9 version now, with some federation support.

https://github.com/pixelfed/pixelfed/releases/tag/v0.5.9
(and a few other minor releases: https://github.com/pixelfed/pixelfed/releases)

@Jibec do you need help to test the package ?

**Comment by Jibec** [comment]
Last time I tried, it was the nginx basic config creating difficulties. If you may help there, I assume it would really help. Time also is an issue.

**Comment by Jibec** [comment]
thanks to @yalh76 , we now have something that can be tested, please have a look at testing branch. I'll ping both of you in the coming days, when we'll open the PR from testing to master, so you can be beta-tester :)

**Comment by lapineige** [comment]
I'm willing to test it too :slightly_smiling_face:

**Comment by yalh76** [comment]
Yes it took a lot of time because of the installation of PHP7.2

The `Warning: fatal: Not a git repository (or any of the parent directories): .git` is not a problem, generated by `php7.2 artisan horizon:purge`

Federation need to be activated in the .env file, maybe we can activate it by default ?

https://github.com/YunoHost-Apps/pixelfed_ynh/blob/3c2a90d70272c033c77bbf92c9a0489b7fd8b7ff/conf/.env#L66-L72

**Comment by lapineige** [comment]
I think people expect it to be activated by default.


But it doesn't seem to be very effective, I activated it, now I can see my account from mastodon (but no statuses), I can try to follow, but I see the hourglass and it's not validated (it's apparently a general Pixelfed issue, not related to Yunohost. We'll see if 0.9 fix that).
The public timeline is empty.

More feedback: there is no preview generated for the images in my instance.

**Comment by lapineige** [comment]
Horizon (what is it ?) doesn't work on my side, I have an error page.
Is it the same for you ?

**Comment by yalh76** [comment]
> 
> 
> Horizon (what is it ?) doesn't work on my side, I have an error page.
> Is it the same for you ?

Horizon seems to be a part of the php framework used to build Pixelfed.

**Comment by lapineige** [comment]
Pixelfed v0.9 is being released: https://github.com/pixelfed/pixelfed/releases/tag/v0.9.0

I suggest that we polish the testing branch for 0.8.4, then merge it into master (that would already be a huge change), and next update to 0.9.x in testing branch. What do you think ?

**Comment by yalh76** [comment]
> 
> 
> Pixelfed v0.9 is being released: https://github.com/pixelfed/pixelfed/releases/tag/v0.9.0
> 
> I suggest that we polish the testing branch for 0.8.4, then merge it into master (that would already be a huge change), and next update to 0.9.x in testing branch. What do you think ?

V0.9.0 implementation started in PR #36

**Comment by yalh76** [comment]
pixelfed_ynh will be upgrade to 0.9.0 soon https://github.com/YunoHost-Apps/pixelfed_ynh/pull/39
