### ISSUE TITLE
Account verification doesn't work

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/pixelfed_ynh#63]
Hello,

I created an account, but the link of the verification mail gives me a blank page. Literally, the page's size is 0 bytes. And my account is still unverified.

**Comment by yalh76** [comment]
did it was your first account created ?
I've made that a lot of time, and nether get this issue...

did the account was already admin before using the link verification ?

**Comment by stemy2** [comment]
Yes, this is the first. An the account is not already admin.

**Comment by yalh76** [comment]
well, nether add that issue, do you tried to open the link from another browser or another computer ?

**Comment by stemy2** [comment]
Yes, same problem everywhere.

**Comment by yalh76** [comment]
well in that case, you can try to remove and reinstall to see if it works

**Comment by raphgilles** [comment]
I don't know if it's the same thing, but on my instance I has to disable the verification mail in my .env because it gave an error page (with the cat).

**Comment by yalh76** [comment]
not sure if a blank page and the kitty page is the same error.

If someone can provide nginx logs when that happens, would be helpfull...

No one reporting mail verification issues in pixelfed upstream repository. Maybe it's pixelfed_ynh or YunoHost or server related (for example, only happens on Raspberry Pi, and the only guys enough crazy to install pixelfed on Raspberry Pi are Yunohosters)

**Comment by raphgilles** [comment]
I have just the ynh_overlay & ynh_portal in the error.log

```
2019/06/06 21:27:16 [error] 15719#15719: *53171 open() "/var/www/pixelfed/public/ynh_portal.js" failed (2: No such file or directory), client: 2a01:cb1d:83b4:1b00:b0b9:a4eb:bd0:945e, server: pixelfed.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "pixelfed.fr", referrer: "https://pixelfed.fr/i/verify-email"
2019/06/06 21:27:16 [error] 15719#15719: *53171 open() "/var/www/pixelfed/public/ynh_overlay.css" failed (2: No such file or directory), client: 2a01:cb1d:83b4:1b00:b0b9:a4eb:bd0:945e, server: pixelfed.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "pixelfed.fr", referrer: "https://pixelfed.fr/i/verify-email"
2019/06/06 21:27:18 [error] 15719#15719: *53171 open() "/var/www/pixelfed/public/ynh_portal.js" failed (2: No such file or directory), client: 2a01:cb1d:83b4:1b00:b0b9:a4eb:bd0:945e, server: pixelfed.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "pixelfed.fr", referrer: "https://pixelfed.fr/i/verify-email"
2019/06/06 21:27:18 [error] 15719#15719: *53171 open() "/var/www/pixelfed/public/ynh_overlay.css" failed (2: No such file or directory), client: 2a01:cb1d:83b4:1b00:b0b9:a4eb:bd0:945e, server: pixelfed.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "pixelfed.fr", referrer: "https://pixelfed.fr/i/verify-email"
```

**Comment by yalh76** [comment]
That normal, it's related to https://github.com/YunoHost-Apps/pixelfed_ynh/issues/41, not solved yet, but no relations between that and the blank page

**Comment by yalh76** [comment]
can you test with the last pixelfed_ynh. php parameters have been changed.
you can execute:
`yunohost app install https://github.com/YunoHost-Apps/pixelfed_ynh --debug`

**Comment by stemy2** [comment]
OK, it works now.

**Comment by renaudponcelet** [comment]
For me the verification link leads me to : "
Sorry, this page isn't available.

The link you followed may be broken, or the page may have been removed. Go back to Pixelfed.
"

**Comment by yalh76** [comment]
Can you provide the url of the verification link ?

**Comment by renaudponcelet** [comment]
Of course : 
https://pixelfed.zetmus.fr/i/confirm-email/PKiUPxhe37zd9xVJxpvaJJDxPeLvMn0kPlQYq2igAgSJGo2kX4fq2ofa2oOqowZs/MQPSzN7UQH0IuLN99zlHNtc5FsIuEV0gnIBYC9R8COZyw4HYdmP7wSga5omTHm6CRdo6VHMqtjgXlKCKzYRwtF2f3sqmvhegLLrELT2AxQ67bPT4AUgaRwd1r5LQdIrQ

**Comment by yalh76** [comment]
I don't know is you made some changes but the link you provided seems to work for me and I was able to register an account on your pixelfed instance without email confirmation...

If you can delete the account I created

**Comment by renaudponcelet** [comment]
I disabled email confiramation meanwhile.. Sorry.
I should be able to confirm my email adress anyway but i still have the same issue.
And that brings me to the same page when i try to delete your acount.

**Comment by yalh76** [comment]
can you check if the horizon service works ?
Doing `service pixelfed-horizon status`

**Comment by yalh76** [comment]
Welle, really don't understand what can happen, maybe you should ask at Pixelfed of wait to the next release

**Comment by renaudponcelet** [comment]
Ok, thank you for you help
