### ISSUE TITLE
Could not open input file: artisan

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/pixelfed_ynh#70]
Bonjour,

J'ai ce message d'erreur chaque fois que je lance une commande contenant «artisan». Voici les logs d'install.

https://stemy.me/zerobin/?96ab7f4482d42264#NDYkhhB/yShWnyXEPEe8BQ3TbpASnTGBZV4XpGzM5oM=

**Comment by yalh76** [comment]
La commande artisan tu la lances bien depuis le dossier pixelfed ?
En utilisant, `php7.2 artisan la_commande_que_tu veux_lancer` ?

**Comment by stemy2** [comment]
Oui.

**Comment by yalh76** [comment]
est ce que tu peux indiquer le message d'erreur que tu rencontres en lançant une commande php7.2 artisan ?

**Comment by stemy2** [comment]
J'avais simplement oublié de me mettre en root.
