### ISSUE TITLE
OSError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by lesamarien** [YunoHost-Apps/pixelfed_ynh#72]
Bonjour

je viens de tenter une nouvelle mise à jour et j'ai le message suivant : 

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/moulinette/utils/stream.py", line 47, i                                        n run
    data += os.read(self._fd, 50)
OSError: [Errno 11] Resource temporarily unavailable

**Comment by lesamarien** [comment]
Et ses 2 messages également : 

Warning: /etc/apt/trusted.gpg.d/extra_php_version.asc wasn't deleted because it doesn't exist.
Warning: fatal: Not a git repository (or any of the parent directories): .git

PixelFed fonctionne mais est-ce à cause de ces erreurs que la partie notifications ne fonctionne pas et que la partie alerte est en constante recherche sans résultat.

**Comment by raphgilles** [comment]
Salut !

Alors pour les notifications, c'est un problème lié au package officiel. Il a été remonté sur le Github du projet, et sera donc vraisemblablement corrigé dans une future maj.

Pour le reste, tu fais bien `sudo yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/ --debug`
et non pas `git pull origin dev` ?

**Comment by yalh76** [comment]
@lesamarien est ce que tu peux fournir le liens vers un pastebin des logs complets, parce qu'avec ce que tu fournis impossible de savoir ou peut être ton probléme.

Concernant les deux warnings, rien d'inquiétant

**Comment by lesamarien** [comment]
Oui j'ai bien fait : sudo yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/

Et apparemment, c'est un problème connu, vu sur le github de Pixelfed. Attendons une mise à jour pour voir si le problème sera résolu...

**Comment by yalh76** [comment]
Tu peux mettre le lien vers l'issue correspondante du github de pixelfed ?
