### ISSUE TITLE
Has Loops been rolled out on Yunohost

### ISSUE THREAD

**Issue by StopTrackingUs** [YunoHost-Apps/pixelfed_ynh#73]
Just a question.  I also am not seeing the suggestions functionality.

**Comment by yalh76** [comment]
I don't know. 

It seems that loops have added in 0.9.4 https://github.com/pixelfed/pixelfed/releases/tag/v0.9.4

And for suggestions features, you have to look at the pixelfed upstream repository https://github.com/pixelfed/pixelfed

But it's still a beta version.

**Comment by StopTrackingUs** [comment]
For experimental functionality you need the following env variables:

EXP_LC=true
EXP_REC=true
EXP_NS=true
EXP_LOOPS=true
INSTANCE_CONTACT_EMAIL=infiniteself@helpchangethe.world
MEDIA_TYPES='image/jpeg,image/png,image/gif,video/mp4'
PF_OPTIMIZE_VIDEOS=true

you also need to run 'sudo apt-get install ffmpeg' for video support if it is not installed already.

**Comment by StopTrackingUs** [comment]
Federation and remote follow has been rolled out to the upstream.

**Comment by lapineige** [comment]
It works with this env variables, thanks :)

**Comment by yalh76** [comment]
Well, as the functionalities are still experimental, this parameters not in the .env.example of the upstream application and there is no documentation for thoses parameters https://docs.pixelfed.org/master/configuration.html.
I propose to not include them in the pixelfed_ynh configuration

**Comment by StopTrackingUs** [comment]
@yalh76 the actual configuration file is at pixelfed/config/pixelfed.php.  You can see it in the upstream here https://github.com/pixelfed/pixelfed/blob/dev/config/pixelfed.php and in the above directory on deployed ynh pixelfed servers.  Experimental .env variables are in the /config/exp.php file.  None of my post here are to lead anyone wrong. Just to pass on information received from @Dansup in the upstream and IRC conversations with @Dansup.  That being said please don't add my email as your instance contact lol.

**Comment by StopTrackingUs** [comment]
An example of loops rolled out on a ynh hosted instance is https://pixels.helpchangethe.world/p/InfiniteSelf/44214132886605824
