### ISSUE TITLE
Impossible de supprimer un compte

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/pixelfed_ynh#74]
Hello,

Quand j'essaye de supprimer un utilisateur via le panneau d'administration, ça me donne un «page not found» quand je clique sur «Delete account».

**Comment by StopTrackingUs** [comment]
I do not know if account deletion is set up right now from the UI you can delete accounts from the command using 
`sudo php7.2 artisan user:delete [userid]`

Answer yes to the question of if you want to delete the user.  Then type in the username to complete deletion.

**Comment by StopTrackingUs** [comment]
I am helping the upstream out with documentation.  A complete list of artisan commands are in my repo and once I make all the updates I will submit a pull to the upstream so that the documentation site will be updated.

https://github.com/StopTrackingUs/docs/blob/master/master/running-an-instance/artisan-command.md

**Comment by stemy2** [comment]
@StopTrackingUs Your command doesn't work for admin account, it says «Cannot delete an admin account from CLI.»

**Comment by StopTrackingUs** [comment]
Oh.  Thats an interesting one.  I would not have guessed you were trying to delete an admin account.  I would add this as an issue in the upstream.

**Comment by StopTrackingUs** [comment]
A work around would be to use the user:admin command to remove admin from the user then try and delete them again.

**Comment by yalh76** [comment]
Hi @stemy2 

I have tested to delete a "normal" user, here is the result:
![Capture](https://user-images.githubusercontent.com/30271971/59457780-63ba6f80-8e19-11e9-8154-bfee09df523f.PNG)

So you have to use the command provided by @StopTrackingUs. 

And to delete an admin user, maybe first removing is admin status doing `(cd /var/www/pixelfed && php7.2 artisan user:admin 1)`
