### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/pixelfed_ynh#75]
Hello,

I tried to upgrade via the command «yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh», but it gives me the following error message: https://paste.yunohost.org/raw/kikisoloro

**Comment by yalh76** [comment]
Salut @stemy2 

Est ce que tu essayer de mettre à jour en exécutant : `yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/tree/debug -- debug` et envoyer le lien vers le log

**Comment by stemy2** [comment]
> Salut @stemy2
> 
> Est ce que tu essayer de mettre à jour en exécutant : `yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/tree/debug -- debug` et envoyer le lien vers le log

C'est précisément ce que je viens de faire.

**Comment by yalh76** [comment]
> 
> 
> > Salut @stemy2
> > Est ce que tu essayer de mettre à jour en exécutant : `yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/tree/debug -- debug` et envoyer le lien vers le log
> 
> C'est précisément ce que je viens de faire.

t'as vu que ça pointait vers une nouvelle branche ? que j'ai modifié pour que ça dise plus de chose pendant la phase de mise à jour ?

**Comment by stemy2** [comment]
Au temps pour moi, j'avais mal lu.

**Comment by stemy2** [comment]
Voilà: https://stemy.me/zerobin/?d6afe8435613fdaf#EI34TIzYnflwKhh9Mh8CAOM8Wi1HwllETsIRidrzr5A=

**Comment by yalh76** [comment]
Bon encore pas assez de détails, lors de la mise à jour des dépendances avec composer, il y a un échec sans expliquer pourquoi.

J'ai modifié la commande, et lors de la mise il devrait te poser des questions, je vais avoir besoin de savoir quoi comme question il te pose pour pouvoir régler le probléme.

tu peux réexécuter `yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/tree/debug -- debug` et me dire les questions qu'il te pose aprés `DEBUG + php7.2 /var/www/pixelfed/composer.phar dump-autoload -d /var/www/pixelfed --verbose`

**Comment by stemy2** [comment]
J'ai lancé la commande et ça ne m'a posé aucune question. Et j'ai l'impression que la sortie est en tout points identique à la précédente: https://paste.yunohost.org/raw/romupabeco

**Comment by yalh76** [comment]
En fait non, ça a changé à partir de la ligne que je t'avais indiqué Ligne 2001: https://paste.yunohost.org/romupabeco

Est ce que tu peux lancer la commande :
`(cd /var/www/pixelfed && php7.2 /var/www/pixelfed/composer.phar update -d /var/www/pixelfed --verbose)`
Et me dire ce que cela donne.

**Comment by stemy2** [comment]
Ça donne ceci:

```
root@stemy:/home/admin# (cd /var/www/pixelfed && php7.2 /var/www/pixelfed/composer.phar update -d /var/www/pixelfed --verbose)
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

**Comment by yalh76** [comment]
et rien d'autre ? ou il a pas encore fini ?

**Comment by stemy2** [comment]
Non, rien d'autre.

**Comment by yalh76** [comment]
il n'est pas revenu au prompt ? en écrivant `root@stemy:/home/admin#`

**Comment by stemy2** [comment]
Si.

**Comment by yalh76** [comment]
Etrange et bizarre, la commande `php7.2 /var/www/pixelfed/composer.phar update -d /var/www/pixelfed --verbose` c'est la commande sur laquelle il bloquait.

Tu peux peut être réessayer d'éxécuter `yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/tree/debug --debug` mais là j'ai plus d'autres pistes
