### ISSUE TITLE
How to change storage quotas ?

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/pixelfed_ynh#77]
Hello,

I see the default quota is 1GB and i'd like to set it to «unlimited», but i dont see such parameter in the .env file. How can i do that ?

There is no «LIMIT_ACCOUNT_SIZE» in my .env file, and adding it manually with the parameter «false» doesn't do anything.

**Comment by yalh76** [comment]
Hi @stemy2 

You have the information in the documentation [RTFM](https://docs.pixelfed.org/master/configuration.html)

**Comment by stemy2** [comment]
Actually, i have read the documentation, this is why i know that i have to set LIMIT_ACCOUNT_SIZE to «false». But as i said, the problem is that this parameter is not present in my .env file. And nothing changed when i added «LIMIT_ACCOUNT_SIZE=false» manually and reloaded the cache.

**Comment by yalh76** [comment]
After making the configuration changes, did you execute:
```
(cd /var/www/pixelfed && php7.2 artisan config:clear)
(cd /var/www/pixelfed && php7.2 artisan config:cache)
```

**Comment by stemy2** [comment]
Yes.
