### ISSUE TITLE
Update to 0.9.6

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/pixelfed_ynh#78]
Pixelfed 0.9.6 is out https://github.com/pixelfed/pixelfed/releases/tag/v0.9.6
With quite a massive number of changes.

I'm available to test a PR :)

**Comment by yalh76** [comment]
Don’t hésitante tout do à PR ;)

**Comment by lapineige** [comment]
Well I was thinking is was more complex that just updating the source, I tried anyway… it worked for me :tada:

**Comment by yalh76** [comment]
🎉🎉🎉 I knew you were able to do it ;) 🎉🎉🎉

**Comment by lapineige** [comment]
Hopefully they were no more thing to do with php artisan stuff and so on :sweat_smile:

**Comment by yalh76** [comment]
If there was, I'm sure you found what to add and where to add it ;)

**Comment by lapineige** [comment]
And a few headache first 😆

**Comment by yalh76** [comment]
@lapineige 
Do you have a list of enhancement for 0.9.6, I didn't found it

**Comment by lapineige** [comment]
They are not yet written.
