### ISSUE TITLE
Please consider using ynh_install_php

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/pixelfed_ynh#8]
Hi

We noticed that you use an another version of php than the current version of stretch. Installing another version of php can (will probably) breaks YunoHost for other apps.
Please consider using the experimental helper [ynh_install_php](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_install_php/ynh_install_php) to handle securely other version of php.

If you encounter any problem using this helper, please open an issue on the repo.

**Comment by Jibec** [comment]
Hi, thanks for this helper and the notice, @yalh76 did the replacement.
