### ISSUE TITLE
 «Oops, something went wrong» after upgrade to v0.10.6

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/pixelfed_ynh#86]
Hello,

I can't use pixelfed anymore since the last update. After logging on, i have the message «Oops, something went wrong». I tried the solution mentioned [there](https://github.com/pixelfed/pixelfed/issues/694), but it solved nothing.

**Comment by yalh76** [comment]
Sorry, without logs, we can't help you.

**Comment by lapineige** [comment]
@stemy2 did the upgrade worked correctly ? (no error message)

**Comment by lapineige** [comment]
I upgraded again to the same version (from v0.10.6), and now I have this error…

> connect() to unix:/var/run/php/php7.3-fpm-pixelfed.sock failed (2: No such file or directory) while connecting to upstream, client: 136.243.88.169, server: domain.tld, request: "POST /users/Pseudo/inbox HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm-pixelfed.sock:", host: "domain.tld"
>FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/pixelfed/vendor/composer/../spatie/laravel-backup/src/Helpers/functions.php): failed to open stream: No such file or directory in /var/www/pixelfed/vendor/composer/autoload_real.php on line 66 
> PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/pixelfed/vendor/composer/../spatie/laravel-backup/src/Helpers/functions.php' (include_path='.:/usr/share/php') in /var/www/pixelfed/vendor/composer/autoload_real.php on line 66" while reading response header from upstream, client: 116.203.17.124, server: domain.tld, request: "GET /api/v1/instance HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm-pixelfed.sock:", host: "domain.tld"

**Comment by lapineige** [comment]
Note: everything works except the main timeline.

**Comment by lapineige** [comment]
@yalh76 can you reopen this issue ? Thanks :)

**Comment by lesamarien** [comment]
[log-install-pixelfed.txt](https://github.com/YunoHost-Apps/pixelfed_ynh/files/3873554/log-install-pixelfed.txt)

Hello

I just installed Pixelfed 0.10.6 on my Yunohost 3.6.5.3. The installation went well. I created my account and put in admin.
When I connect, I have the same problem, I have the following message:

**"Oops, something went wrong
Please reload the page. "**

I manage to post photos but in the home page, there is a circle constantly rotates and does not display the photos.

I enclose the installation log if it can help you.

Thank you for your help

**Comment by lapineige** [comment]
Restarting `php7.3-fpm` did work… it's strange, I'm sure that one of the first things I tried.
Solved for me

**Comment by nr458h** [comment]
@lapineige, greate to hear that you found a solution.
Running `service php7.3-fpm restart` didn't solve the problem for me.

Any other ideas?

My szenario is similar to @lesamarien (new installation)

**Comment by lapineige** [comment]
And mine was only an upgrade (from the same version ^^).

Can you check php logs ? (after going to Pixelfed, to the page where you have this issue)

**Comment by nr458h** [comment]
sadly there is nothing in the logs (via GUI php7.3-fpm)

**Comment by lapineige** [comment]
No error or warning at all after encountering the issue ?

I have the issue again…
And also any post with a # is not well federated, has no title displayed in my Pixelfed (but it's fine from somewhere else, including Mastodon)

**Comment by lesamarien** [comment]
Hello

After updating Yunohost, an update of PHP7.3 has been made and Pixelfed is working again.

**Comment by lapineige** [comment]
For me, it seems to be the contrary: it fails since the last update.

**Comment by lapineige** [comment]
I don't find any relevant log…
When I have this issue, the log says:
> [pool pixelfed] child 17839, script '/var/www/pixelfed/public/index.php' (request: "POST /index.php?/api/pixelfed/v1/media") executing too slow (5.790417 sec), logging
> [pool pixelfed] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 0 idle, and 6 total children
> [pool pixelfed] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 0 idle, and 6 total children

**Comment by lapineige** [comment]
I tried to "upgrade" again to the same version, still the same issue…
@yalh76 have you any idea about how I can provide more logs or debug this ?

**Comment by nr458h** [comment]
After an update today the error was gone but came back to life when I opened the registration and let one person run a registration.
(still nothing in the logs) maybe this is helpful

**Comment by lapineige** [comment]
Fixed by #91 
I hope it will last this time… 😄

**Comment by yalh76** [comment]
> 
> 
> Fixed by #91
> I hope it will last this time… 😄

Thanks a lot, I will check that PR

**Comment by lapineige** [comment]
I have this issue again… 😞
I think I've found what's the problem : it happens (at least for now, I don't know for the past issues) only if I add alternative text to my image.

**Comment by yalh76** [comment]
> 
> 
> I have this issue again… 😞
> I think I've found what's the problem : it happens (at least for now, I don't know for the past issues) only if I add alternative text to my image.

And do you know if it's YunoHost specific ?

**Comment by lapineige** [comment]
No, and I don't see a way to make sure it is (not) related to Yunohost.

**Comment by yalh76** [comment]
Maybe you should ask at the upstream app ;p

**Comment by stemy2** [comment]
For me, the problem is solved.
