### ISSUE TITLE
It's ready :-)

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/pixelfed_ynh#9]
https://mastodon.social/@dansup/101812886435916233

**Comment by Jibec** [comment]
hello, thank you for the reminder, but please don't open issues like this ;)

**Comment by dosch** [comment]
Sorry :-)

Because you stated: "I'm waiting for an official release (alpha/beta or stable) to invest more time on this package. Don't hesitate to give a hand if you wish, I assume only the nginx file needs improvments." in your readme, I thought you might wanted to know.

**Comment by Jibec** [comment]
👍
